# WhatATheme
markdown: kramdown

# URL of the Site
url: 'rytt0001.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ryan Sandrin
# Description of the Site
description: C++ and c# generalist developer
# URL of Image of the Site
site-image: /assets/images/sample_cover.jpg
# Keywords of the Site
site-keywords: portfolio, projects, ryan sandrin, SOLID TEAM
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/sample_cover.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ryan.sandrin@outlook.fr
facebook_username:
twitter_username:
instagram_username:
linkedin_username: ryan-sandrin
github_username:  rytt0001
youtube_channel_id:
reddit_username: rytt0001
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: rytt0001

# Name of the Author
author-name: Rytt0001
# URL for the Image of the Author
author-image: /assets/images/profile.png
# 60 Words About the Author
author-about: C++ and C# developer and sometimes gamers, I like to make jokes to ease tension in the atmosphere
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/rytt0001

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
#compress_html:
#  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page
  -
    scope:
      type: 'projects'
    values:
      layout: project
      
      
collections:
    project:
        output: true
# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
